include(${CMAKE_CURRENT_SOURCE_DIR}/CMake/FindWpiPackage.cmake)

if(GET_SHARED_LIBS)
    list(APPEND opencv_libs "opencv_aruco")
    list(APPEND opencv_libs "opencv_calib3d")
    list(APPEND opencv_libs "opencv_core")
    list(APPEND opencv_libs "opencv_dnn")
    list(APPEND opencv_libs "opencv_features2d")
    list(APPEND opencv_libs "opencv_flann")
    list(APPEND opencv_libs "opencv_gapi")
    list(APPEND opencv_libs "opencv_highgui")
    list(APPEND opencv_libs "opencv_imgcodecs")
    list(APPEND opencv_libs "opencv_imgproc")
    list(APPEND opencv_libs "opencv_ml")
    list(APPEND opencv_libs "opencv_objdetect")
    list(APPEND opencv_libs "opencv_photo")
    list(APPEND opencv_libs "opencv_stitching")
    list(APPEND opencv_libs "opencv_video")
    list(APPEND opencv_libs "opencv_videoio")
else()
    list(APPEND opencv_libs "opencv480")
endif()

list(APPEND CMAKE_FIND_LIBRARY_SUFFIXES .so.4.8)
list(APPEND CMAKE_FIND_LIBRARY_SUFFIXES .so.4.8.debug)

FindWpiPackage(opencv "${opencv_libs}" "4.8.0-2" "" YES GetThirdpartyUrl)